# : Manager [[[

[manager]
cwd = { fg = "#e6e0ef" }

# Tab
tab_active = { fg = "#340098", bg = "#cbbeff", bold = true }
tab_inactive = { fg = "#e7deff", bg = "#1e0061" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#f870ff", bg = "#f870ff" }
marker_cut = { fg = "#fdd6ff", bg = "#fdd6ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e5b8e9", bg = "#e5b8e9" }

# Count
count_copied = { fg = "#2e0d35", bg = "#fdd6ff" }
count_cut = { fg = "#2e0d35", bg = "#fdd6ff" }
count_selected = { fg = "#340098", bg = "#e5b8e9" }

# Border
border_symbol = "│"
border_style  = { fg = "#cbbeff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#340098", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#cbbeff", fg = "#340098", bold = true }
normal_alt  = { bg = "#484551", fg = "#cac4d2" }

# Select mode
select_main = { bg = "#d4bee6", fg = "#392a49", bold = true }
select_alt  = { bg = "#484551", fg = "#cac4d2" }

# Unset mode
unset_main = { bg = "#e5b8e9", fg = "#45234b", bold = true }
unset_alt  = { bg = "#484551", fg = "#cac4d2" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#cbbeff", bg = "#3a3843" }
progress_error = { fg = "#ffb4ab", bg = "#3a3843" }

# Permissions
permissions_t = { fg = "#8b50bc" }
permissions_w = { fg = "#ba43c5" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#f63dff" }
permissions_s = { fg = "#7845ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#cbbeff" }
active = { fg = "#e5b8e9", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#cbbeff" }
value = { fg = "#e6e0ef" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#cbbeff", bg = "#340098" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#cbbeff" }
title = {}
hovered = { fg = "#fdd6ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a3843" }
cand = { fg = "#cbbeff" }
rest = { fg = "#340098" }
desc = { fg = "#e6e0ef" }
separator = " ▶ "
separator_style = { fg = "#e6e0ef" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e6e0ef" }
run = { fg = "#e6e0ef" }
footer = { fg = "#392a49", bg = "#d4bee6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e5b8e9" }
title_warn = { fg = "#cbbeff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e6e0ef" },
    { name = "*/", fg = "#cbbeff" },
]

# : ]]]
[flavor]
dark  = "noctalia"
light = "noctalia"
